version: '3'

services:
  ws_py_grpc_demo:
    container_name: ws_py_grpc_demo
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile_DEV
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/app/ws_py_grpc_demo
    expose:
      - 443
    networks:
      - wservice_workspace_default
    stdin_open: true
    tty: true

networks:
  wservice_workspace_default:
    external: true
