# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/calculator.proto\x12\ncalculator\"/\n\x11\x43\x61lculatorRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04num2\x18\x02 \x01(\x01\"$\n\x12\x43\x61lculatorResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\xac\x02\n\nCalculator\x12\x46\n\x03\x41\x64\x64\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\"\x00\x12\x46\n\x03Sub\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\"\x00\x12\x46\n\x03Mul\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\"\x00\x12\x46\n\x03\x44iv\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\"\x00\x62\x06proto3')



_CALCULATORREQUEST = DESCRIPTOR.message_types_by_name['CalculatorRequest']
_CALCULATORRESPONSE = DESCRIPTOR.message_types_by_name['CalculatorResponse']
CalculatorRequest = _reflection.GeneratedProtocolMessageType('CalculatorRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATORREQUEST,
  '__module__' : 'proto.calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculatorRequest)
  })
_sym_db.RegisterMessage(CalculatorRequest)

CalculatorResponse = _reflection.GeneratedProtocolMessageType('CalculatorResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATORRESPONSE,
  '__module__' : 'proto.calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculatorResponse)
  })
_sym_db.RegisterMessage(CalculatorResponse)

_CALCULATOR = DESCRIPTOR.services_by_name['Calculator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCULATORREQUEST._serialized_start=38
  _CALCULATORREQUEST._serialized_end=85
  _CALCULATORRESPONSE._serialized_start=87
  _CALCULATORRESPONSE._serialized_end=123
  _CALCULATOR._serialized_start=126
  _CALCULATOR._serialized_end=426
# @@protoc_insertion_point(module_scope)
